/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsAboutRouteImport } from './routes/settings.about'
import { Route as SettingsAccountRouteImport } from './routes/settings.account'
import { Route as SettingsBlockedDevicesRouteImport } from './routes/settings.blocked-devices'
import { Route as SettingsChatsRouteImport } from './routes/settings.chats'
import { Route as SettingsDevicesRouteImport } from './routes/settings.devices'
import { Route as SettingsEditProfileRouteImport } from './routes/settings.edit-profile'
import { Route as SettingsFoldersRouteImport } from './routes/settings.folders'
import { Route as SettingsHelpRouteImport } from './routes/settings.help'
import { Route as SettingsLanguageRouteImport } from './routes/settings.language'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsPowerRouteImport } from './routes/settings.power'
import { Route as SettingsPrivacyRouteImport } from './routes/settings.privacy'
import { Route as SettingsQrRouteImport } from './routes/settings.qr'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as SettingsSocialLinksRouteImport } from './routes/settings.social-links'
import { Route as SettingsStorageRouteImport } from './routes/settings.storage'
import { Route as SettingsSecurityAutoLockRouteImport } from './routes/settings.security.auto-lock'
import { Route as SettingsSecurityFingerprintRouteImport } from './routes/settings.security.fingerprint'
import { Route as SettingsSecurityPasswordRouteImport } from './routes/settings.security.password'
import { Route as SettingsSecurityPinRouteImport } from './routes/settings.security.pin'
import { Route as SettingsSecurityRecoveryRouteImport } from './routes/settings.security.recovery'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/settings/about',
  path: '/settings/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBlockedDevicesRoute = SettingsBlockedDevicesRouteImport.update({
  id: '/settings/blocked-devices',
  path: '/settings/blocked-devices',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsChatsRoute = SettingsChatsRouteImport.update({
  id: '/settings/chats',
  path: '/settings/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDevicesRoute = SettingsDevicesRouteImport.update({
  id: '/settings/devices',
  path: '/settings/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsEditProfileRoute = SettingsEditProfileRouteImport.update({
  id: '/settings/edit-profile',
  path: '/settings/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsFoldersRoute = SettingsFoldersRouteImport.update({
  id: '/settings/folders',
  path: '/settings/folders',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHelpRoute = SettingsHelpRouteImport.update({
  id: '/settings/help',
  path: '/settings/help',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLanguageRoute = SettingsLanguageRouteImport.update({
  id: '/settings/language',
  path: '/settings/language',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPowerRoute = SettingsPowerRouteImport.update({
  id: '/settings/power',
  path: '/settings/power',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/settings/privacy',
  path: '/settings/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsQrRoute = SettingsQrRouteImport.update({
  id: '/settings/qr',
  path: '/settings/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSocialLinksRoute = SettingsSocialLinksRouteImport.update({
  id: '/settings/social-links',
  path: '/settings/social-links',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsStorageRoute = SettingsStorageRouteImport.update({
  id: '/settings/storage',
  path: '/settings/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityAutoLockRoute =
  SettingsSecurityAutoLockRouteImport.update({
    id: '/auto-lock',
    path: '/auto-lock',
    getParentRoute: () => SettingsSecurityRoute,
  } as any)
const SettingsSecurityFingerprintRoute =
  SettingsSecurityFingerprintRouteImport.update({
    id: '/fingerprint',
    path: '/fingerprint',
    getParentRoute: () => SettingsSecurityRoute,
  } as any)
const SettingsSecurityPasswordRoute =
  SettingsSecurityPasswordRouteImport.update({
    id: '/password',
    path: '/password',
    getParentRoute: () => SettingsSecurityRoute,
  } as any)
const SettingsSecurityPinRoute = SettingsSecurityPinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => SettingsSecurityRoute,
} as any)
const SettingsSecurityRecoveryRoute =
  SettingsSecurityRecoveryRouteImport.update({
    id: '/recovery',
    path: '/recovery',
    getParentRoute: () => SettingsSecurityRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/blocked-devices': typeof SettingsBlockedDevicesRoute
  '/settings/chats': typeof SettingsChatsRoute
  '/settings/devices': typeof SettingsDevicesRoute
  '/settings/edit-profile': typeof SettingsEditProfileRoute
  '/settings/folders': typeof SettingsFoldersRoute
  '/settings/help': typeof SettingsHelpRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/power': typeof SettingsPowerRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/qr': typeof SettingsQrRoute
  '/settings/security': typeof SettingsSecurityRouteWithChildren
  '/settings/social-links': typeof SettingsSocialLinksRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/security/auto-lock': typeof SettingsSecurityAutoLockRoute
  '/settings/security/fingerprint': typeof SettingsSecurityFingerprintRoute
  '/settings/security/password': typeof SettingsSecurityPasswordRoute
  '/settings/security/pin': typeof SettingsSecurityPinRoute
  '/settings/security/recovery': typeof SettingsSecurityRecoveryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/blocked-devices': typeof SettingsBlockedDevicesRoute
  '/settings/chats': typeof SettingsChatsRoute
  '/settings/devices': typeof SettingsDevicesRoute
  '/settings/edit-profile': typeof SettingsEditProfileRoute
  '/settings/folders': typeof SettingsFoldersRoute
  '/settings/help': typeof SettingsHelpRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/power': typeof SettingsPowerRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/qr': typeof SettingsQrRoute
  '/settings/security': typeof SettingsSecurityRouteWithChildren
  '/settings/social-links': typeof SettingsSocialLinksRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/security/auto-lock': typeof SettingsSecurityAutoLockRoute
  '/settings/security/fingerprint': typeof SettingsSecurityFingerprintRoute
  '/settings/security/password': typeof SettingsSecurityPasswordRoute
  '/settings/security/pin': typeof SettingsSecurityPinRoute
  '/settings/security/recovery': typeof SettingsSecurityRecoveryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/blocked-devices': typeof SettingsBlockedDevicesRoute
  '/settings/chats': typeof SettingsChatsRoute
  '/settings/devices': typeof SettingsDevicesRoute
  '/settings/edit-profile': typeof SettingsEditProfileRoute
  '/settings/folders': typeof SettingsFoldersRoute
  '/settings/help': typeof SettingsHelpRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/power': typeof SettingsPowerRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/qr': typeof SettingsQrRoute
  '/settings/security': typeof SettingsSecurityRouteWithChildren
  '/settings/social-links': typeof SettingsSocialLinksRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/settings/security/auto-lock': typeof SettingsSecurityAutoLockRoute
  '/settings/security/fingerprint': typeof SettingsSecurityFingerprintRoute
  '/settings/security/password': typeof SettingsSecurityPasswordRoute
  '/settings/security/pin': typeof SettingsSecurityPinRoute
  '/settings/security/recovery': typeof SettingsSecurityRecoveryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings/about'
    | '/settings/account'
    | '/settings/blocked-devices'
    | '/settings/chats'
    | '/settings/devices'
    | '/settings/edit-profile'
    | '/settings/folders'
    | '/settings/help'
    | '/settings/language'
    | '/settings/notifications'
    | '/settings/power'
    | '/settings/privacy'
    | '/settings/qr'
    | '/settings/security'
    | '/settings/social-links'
    | '/settings/storage'
    | '/settings/security/auto-lock'
    | '/settings/security/fingerprint'
    | '/settings/security/password'
    | '/settings/security/pin'
    | '/settings/security/recovery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/about'
    | '/settings/account'
    | '/settings/blocked-devices'
    | '/settings/chats'
    | '/settings/devices'
    | '/settings/edit-profile'
    | '/settings/folders'
    | '/settings/help'
    | '/settings/language'
    | '/settings/notifications'
    | '/settings/power'
    | '/settings/privacy'
    | '/settings/qr'
    | '/settings/security'
    | '/settings/social-links'
    | '/settings/storage'
    | '/settings/security/auto-lock'
    | '/settings/security/fingerprint'
    | '/settings/security/password'
    | '/settings/security/pin'
    | '/settings/security/recovery'
  id:
    | '__root__'
    | '/'
    | '/settings/about'
    | '/settings/account'
    | '/settings/blocked-devices'
    | '/settings/chats'
    | '/settings/devices'
    | '/settings/edit-profile'
    | '/settings/folders'
    | '/settings/help'
    | '/settings/language'
    | '/settings/notifications'
    | '/settings/power'
    | '/settings/privacy'
    | '/settings/qr'
    | '/settings/security'
    | '/settings/social-links'
    | '/settings/storage'
    | '/settings/security/auto-lock'
    | '/settings/security/fingerprint'
    | '/settings/security/password'
    | '/settings/security/pin'
    | '/settings/security/recovery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsBlockedDevicesRoute: typeof SettingsBlockedDevicesRoute
  SettingsChatsRoute: typeof SettingsChatsRoute
  SettingsDevicesRoute: typeof SettingsDevicesRoute
  SettingsEditProfileRoute: typeof SettingsEditProfileRoute
  SettingsFoldersRoute: typeof SettingsFoldersRoute
  SettingsHelpRoute: typeof SettingsHelpRoute
  SettingsLanguageRoute: typeof SettingsLanguageRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPowerRoute: typeof SettingsPowerRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsQrRoute: typeof SettingsQrRoute
  SettingsSecurityRoute: typeof SettingsSecurityRouteWithChildren
  SettingsSocialLinksRoute: typeof SettingsSocialLinksRoute
  SettingsStorageRoute: typeof SettingsStorageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/settings/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/blocked-devices': {
      id: '/settings/blocked-devices'
      path: '/settings/blocked-devices'
      fullPath: '/settings/blocked-devices'
      preLoaderRoute: typeof SettingsBlockedDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/chats': {
      id: '/settings/chats'
      path: '/settings/chats'
      fullPath: '/settings/chats'
      preLoaderRoute: typeof SettingsChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/devices': {
      id: '/settings/devices'
      path: '/settings/devices'
      fullPath: '/settings/devices'
      preLoaderRoute: typeof SettingsDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/edit-profile': {
      id: '/settings/edit-profile'
      path: '/settings/edit-profile'
      fullPath: '/settings/edit-profile'
      preLoaderRoute: typeof SettingsEditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/folders': {
      id: '/settings/folders'
      path: '/settings/folders'
      fullPath: '/settings/folders'
      preLoaderRoute: typeof SettingsFoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/help': {
      id: '/settings/help'
      path: '/settings/help'
      fullPath: '/settings/help'
      preLoaderRoute: typeof SettingsHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/language': {
      id: '/settings/language'
      path: '/settings/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof SettingsLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/power': {
      id: '/settings/power'
      path: '/settings/power'
      fullPath: '/settings/power'
      preLoaderRoute: typeof SettingsPowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/qr': {
      id: '/settings/qr'
      path: '/settings/qr'
      fullPath: '/settings/qr'
      preLoaderRoute: typeof SettingsQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/social-links': {
      id: '/settings/social-links'
      path: '/settings/social-links'
      fullPath: '/settings/social-links'
      preLoaderRoute: typeof SettingsSocialLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/storage': {
      id: '/settings/storage'
      path: '/settings/storage'
      fullPath: '/settings/storage'
      preLoaderRoute: typeof SettingsStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security/auto-lock': {
      id: '/settings/security/auto-lock'
      path: '/auto-lock'
      fullPath: '/settings/security/auto-lock'
      preLoaderRoute: typeof SettingsSecurityAutoLockRouteImport
      parentRoute: typeof SettingsSecurityRoute
    }
    '/settings/security/fingerprint': {
      id: '/settings/security/fingerprint'
      path: '/fingerprint'
      fullPath: '/settings/security/fingerprint'
      preLoaderRoute: typeof SettingsSecurityFingerprintRouteImport
      parentRoute: typeof SettingsSecurityRoute
    }
    '/settings/security/password': {
      id: '/settings/security/password'
      path: '/password'
      fullPath: '/settings/security/password'
      preLoaderRoute: typeof SettingsSecurityPasswordRouteImport
      parentRoute: typeof SettingsSecurityRoute
    }
    '/settings/security/pin': {
      id: '/settings/security/pin'
      path: '/pin'
      fullPath: '/settings/security/pin'
      preLoaderRoute: typeof SettingsSecurityPinRouteImport
      parentRoute: typeof SettingsSecurityRoute
    }
    '/settings/security/recovery': {
      id: '/settings/security/recovery'
      path: '/recovery'
      fullPath: '/settings/security/recovery'
      preLoaderRoute: typeof SettingsSecurityRecoveryRouteImport
      parentRoute: typeof SettingsSecurityRoute
    }
  }
}

interface SettingsSecurityRouteChildren {
  SettingsSecurityAutoLockRoute: typeof SettingsSecurityAutoLockRoute
  SettingsSecurityFingerprintRoute: typeof SettingsSecurityFingerprintRoute
  SettingsSecurityPasswordRoute: typeof SettingsSecurityPasswordRoute
  SettingsSecurityPinRoute: typeof SettingsSecurityPinRoute
  SettingsSecurityRecoveryRoute: typeof SettingsSecurityRecoveryRoute
}

const SettingsSecurityRouteChildren: SettingsSecurityRouteChildren = {
  SettingsSecurityAutoLockRoute: SettingsSecurityAutoLockRoute,
  SettingsSecurityFingerprintRoute: SettingsSecurityFingerprintRoute,
  SettingsSecurityPasswordRoute: SettingsSecurityPasswordRoute,
  SettingsSecurityPinRoute: SettingsSecurityPinRoute,
  SettingsSecurityRecoveryRoute: SettingsSecurityRecoveryRoute,
}

const SettingsSecurityRouteWithChildren =
  SettingsSecurityRoute._addFileChildren(SettingsSecurityRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsBlockedDevicesRoute: SettingsBlockedDevicesRoute,
  SettingsChatsRoute: SettingsChatsRoute,
  SettingsDevicesRoute: SettingsDevicesRoute,
  SettingsEditProfileRoute: SettingsEditProfileRoute,
  SettingsFoldersRoute: SettingsFoldersRoute,
  SettingsHelpRoute: SettingsHelpRoute,
  SettingsLanguageRoute: SettingsLanguageRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPowerRoute: SettingsPowerRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsQrRoute: SettingsQrRoute,
  SettingsSecurityRoute: SettingsSecurityRouteWithChildren,
  SettingsSocialLinksRoute: SettingsSocialLinksRoute,
  SettingsStorageRoute: SettingsStorageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
